function [ximg1,ximg2] = getVisionScanner()
    vrep=remApi('remoteApi');
    [err,sensor1] = vrep.simxGetObjectHandle(0, 'SICK_S300_sensor1#0',...
        vrep.simx_opmode_oneshot_wait);
    [err,sensor2] = vrep.simxGetObjectHandle(0, 'SICK_S300_sensor2#0',...
        vrep.simx_opmode_oneshot_wait);
    [err,res,img1] =...
        vrep.simxGetVisionSensorImage2(0, sensor1,...
            1, vrep.simx_opmode_oneshot_wait);
    [err,res,img2] =...
        vrep.simxGetVisionSensorImage2(0, sensor2,...
            1, vrep.simx_opmode_oneshot_wait);
    ximg1 = double(img1)/256;
    ximg2 = double(img2)/256;
end