[err, kinect1] = vrep.simxGetObjectHandle(0, 'kinect_depth',...
    vrep.simx_opmode_oneshot_wait);
[retCode, res, depth] = ...
    vrep.simxGetVisionSensorDepthBuffer2(0,kinect1, vrep.simx_opmode_oneshot_wait)